config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
	resources :locations
  resources :users
	root 'locations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :locations
end

app/models/location.rb
class Location < ApplicationRecord
	belongs_to :user
	belongs_to :category

	has_attached_file :location_img, styles: { medium: "400x7290>", thumb: "325x475>" ,:export =>{ :quality => 100, :format => 'JPG'}}
	validates_attachment_content_type :location_img, content_type: /\Aimage\/.*\z/

	def self.search_by(search_term)
		where ("LOWER(name) LIKE :search_term"),
		 search_term: "%#{search_term.downcase}%"
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :locations
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configer_permitted_parameters, if: :devise_controller?
  protected

    def configer_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :username , :birthday, :email, :password, :remember_me)}
      devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit( :email, :password, :remember_me)}
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :username , :birthday, :about, :email, :password, :remember_me)}
    end

    
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	before_action :find_location, only: [:show, :edit, :update, :destroy]
	def index
		if params[:category].blank?
		@location = Location.all.order("created_at DESC")
    else
      @category_id = Category.find_by(name: params[:category]).id
      @location = Location.where(:category_id => @category_id)
    end

    if params[:search]
      @search_term = params[:search]
      @location = @location.search_by(@search_term)
    end
	end

	def new
		@location = current_user.locations.build
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def show

	end

	def create
		@location = current_user.locations.build(location_params)
    @location.category_id = params[:category_id]
		if @location.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end

	def update
		if @location.update(location_params)
			redirect_to location_path
		else
			render 'edit'
		end
	end

	def destroy
		@location.destroy
		redirect_to root_path
	end


	private
		def location_params
			params.require(:location).permit(:name, :direction, :phone, :map, :location_img)
		end

		def find_location
			@location = Location.find(params[:id])
		end

		def search_by(search_term)
			where ("LOWER(name) LIKE :search_term"),
			 search_term: "%#{search_term.downcase}"
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliveryService</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "Kaung Htet", root_path, class: "navbar-brand" %>
        </div>
        <ul class="navbar-nav nav">
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
          
        </ul>
        <% if user_signed_in? %>
          <p><%= link_to "New Location", new_location_path, class: "navbar-text navbar-link navbar-right" %></p>
        <% end %>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
          <%= yield %>
    </div>

  </body>
</html>

app/views/locations/_form.html.erb
<%= simple_form_for @location do |f| %>
  <div class="field">
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a category") %>
  </div>
  <%= f.input :name, label: 'Enter the location name please', error: 'This location is mandatory, please specify one' %>
  <%= f.input :location_img, label: 'Upload plz' %>
  <%= f.input :direction , label: 'Enter the Details direction name please' %>
  <%= f.input :phone,  label: 'Phone Number(Do not Enter (09) plz)', hint: "Example: 450001930" %>
  <%= f.input :map, label: 'Use the map direction from Google Map!' %>
  <%= f.button :submit %>
<% end %>

app/views/locations/edit.html.erb
  <div class="container">
    <h1>Edit your Location Here!</h1>

    <%= render 'form' %>
  </div>

app/views/locations/index.html.erb
<div class="row">
	<div class="col-md-3">
		<h3> You can Search Your Location in Here!!!
			<a><%= form_for "",url: locations_path, role: "search" , method: :get do %>
			<%= text_field_tag :search, @search_tearm,placeholder: "Location Name....." %>
			<% end %></a>
		</h3>

		<div class="dropdown">
				 <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Choose Category
				 <span class="caret"></span></button>
				 <ul class="dropdown-menu">
					 <% Category.all.each do |category| %>
					 <li class="<%= 'active' if params[:category] == category.name %>">
						 <%= link_to category.name, locations_path(category: category.name), class: "link" %>
					 </li>
						 <% end %>
				 </ul>
			 </div>
	</div>
	<div class="col-md-9">
			<h2>Lists of the locations!!!</h2>
		<% @location.each do |location| %>
		<div class="col-md-4">
			<div class="message">
				<h3 class="message-title"><%= location.name %></h3>
				<%= link_to "View Locations", location_path(location), class: 'btn-custom' %>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/locations/new.html.erb
<div class="col-md-8 col-md-offset-2">
  <h1>Make a location!</h1>

  <%= render 'form' %>
</div>

app/views/locations/show.html.erb
<div class="col-md-8 col-md-offset-2">
	<div class="message-show">
		<%= image_tag @location.location_img.url(:medium), class: "location-show" %>
		 <h3 style="color: blue">Category: <%= @location.category.name %></h3>
		<h2><%= @location.name %></h2>
		<p class="location-posted-by">This Location is created by <%= @location.user.email %> <%= time_ago_in_words(@location.created_at) %> ago.</p>
		<p class="location-direction"><%=  @location.direction %></p>
		<p>The Phone number is 09<%=  @location.phone %></p>
		<%= link_to "Map Location", @location.map , class: "btn btn-default" %>
		<div>
			<div class="links btn-group">

				<%= link_to "Back", root_path, class: "btn btn-default" %>

				<%# <% if @location.user_id == current_user %>
					<%= link_to "Edit", edit_location_path(@location), class: "btn btn-default" %>

					<%= link_to "Delete", location_path(@location) , method: :delete, data: {confirm: "Are You Sure You want to delete this Location "}, class: "btn btn-default" %>
					<%# <% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<h3><%= @user.first_name %> <%= @user.last_name %></h3>
<h4><%= @user.email %></h4>
<h5><%= @user.about %></h5>